const colors = {
  dark: {
    background: "#12181b", // used for main container bg
    text: "#000",
    accent: "#1fb6ff", // used for inlinecode text color
    muted: "#2d2d2d", // used for inlinecode background color
  },
  light: {
    background: "#f7f6f3",
    text: "#000000",
    accent: "#c7254e",
    muted: "#f9f2f4",
    gray: "#67788a",
  },
  common: {
    gray: "#67788a",
    white: "#fff",
    shadow: "#3b4048",
    black: "#000",
    green: "#00ff08",
    pink: "#ff00d4",
    purple: "#5f00f8",
  },
};

export default {
  title: "Knowledge Base",
  menu: ["Components", "Docs", "Getting Started", "Readme"],
  themeConfig: {
    initialColorMode: "dark",
    fonts: {
      body: "sofia-pro, sans-serif",
    },
    colors: {
      modes: {
        dark: {
          ...colors.dark,
          sidebar: {
            navGroup: colors.dark.white,
            navLinkActive: colors.dark.accent,
            tocLink: colors.dark.accent,
            tocLinkActive: colors.dark.accent,
          },
        },
        light: {
          ...colors.light,
          sidebar: {
            navGroup: "text",
            navLinkActive: colors.dark.accent,
            tocLink: colors.dark.accent,
            tocLinkActive: colors.dark.accent,
          },
        },
      },
    },
    styles: {
      // Container: {
      //   "> h1": {
      //     position: "relative",
      //     fontSize: "1.5em",
      //     fontWeight: "bold",
      //     padding: "10px 0px 10px 70px",
      //     margin: "30px -26px 20px -26px",
      //     color: colors.common.white,
      //     background: "linear-gradient( 90deg,rgb(0 0 0) ,rgb(98 0 255))",
      //     textShadow: `0px 1px 2px ${colors.common.black}`,
      //     boxShadow: "0px 2px 4px #3b4048",
      //     ":after": {
      //       content: '" "',
      //       position: "absolute",
      //       width: 0,
      //       height: 0,
      //       left: 0,
      //       top: "100%",
      //       borderWidth: "5px 10px",
      //       borderStyle: "solid",
      //       borderColor: "#666 #666 transparent transparent",
      //     },
      //     ":before": {
      //       content: '" "',
      //       position: "absolute",
      //       width: 0,
      //       height: 0,
      //       left: "calc(100% - 20px);",
      //       top: "100%",
      //       borderWidth: "5px 10px",
      //       borderStyle: "solid",
      //       borderColor: "#666 #666 transparent transparent",
      //       transform: "scale(-1, 1)",
      //     },
      //   },
      // },
      blockquote: {
        marginLeft: "15px",
        marginLeft: "15px",
        paddingTop: "0",
        paddingBottom: "1px",
        paddingLeft: "25px",
        paddingRight: "25px",
        bg: "none",
        boxShadow: `6px 5px 10px ${colors.common.shadow}`,
        background: "#fff",
        border: "none",
        "> h1": {
          position: "relative",
          fontSize: "2.5em",
          fontWeight: "bold",
          padding: "20px 0px 20px 25px",
          margin: "-1px -45px 20px -45px",
          color: colors.common.white,
          background: "linear-gradient( 90deg,rgb(0 0 0) ,rgb(98 0 255))",
          boxShadow: "0px 2px 4px #3b4048",
          ":after": {
            content: '" "',
            position: "absolute",
            width: 0,
            height: 0,
            left: 0,
            top: "100%",
            borderWidth: "5px 10px",
            borderStyle: "solid",
            borderColor: "#666 #666 transparent transparent",
          },
          ":before": {
            content: '" "',
            position: "absolute",
            width: 0,
            height: 0,
            left: "calc(100% - 20px);",
            top: "100%",
            borderWidth: "5px 10px",
            borderStyle: "solid",
            borderColor: "#666 #666 transparent transparent",
            transform: "scale(-1, 1)",
          },
        },
        " > h2": {
          marginTop: "3rem",
          "> a": {
            color: colors.common.white,
            position: "relative",
            background: colors.common.black,
            padding: "10px 20px",
            marginLeft: "-45px",
            boxShadow: `2px 2px 4px ${colors.common.purple}`,
            borderTopRightRadius: "30px",
            borderBottomRightRadius: "30px",
            color: colors.common.white,
            ":after": {
              content: '" "',
              position: "absolute",
              width: 0,
              height: 0,
              left: 0,
              top: "100%",
              borderWidth: "5px 10px",
              borderStyle: "solid",
              borderColor: "#666 #666 transparent transparent",
            },
          },
        },
        "> h3": {
          "> a": {
            position: "relative",
            background: colors.common.black,
            padding: "5px 20px",
            marginLeft: "-35px",
            boxShadow: `0px 2px 4px ${colors.common.shadow}`,
            borderBottomRightRadius: "30px",
            color: colors.common.white,
            ":after": {
              content: '" "',
              position: "absolute",
              width: 0,
              height: 0,
              left: 0,
              top: "100%",
              borderWidth: "3px 5px",
              borderStyle: "solid",
              borderColor: "#666 #666 transparent transparent",
            },
          },
        },
        "> h4": {
          "> a": {
            color: colors.common.black,
            // position: "relative",
            // background: "linear-gradient( 90deg,rgb(0 0 0) ,rgb(98 0 255))",
            // padding: "10px 20px",
            // marginLeft: "-2px",
            // boxShadow: "0px 2px 4px #3b4048",
            // borderTopRightRadius: "30px",
            // borderBottomRightRadius: "30px",
          },
        },
        "> p": {
          mb: "10px",
        },
        "> table": {
          color: "#fff",
        },
      },
      inlineCode: {
        bg: "muted",
        color: colors.common.green,
        padding: "2px 6px",
        borderRadius: "4px",
        fontSize: ".85em",
      },
      a: {
        color: colors.common.purple,
      },
      strong: {
        fontStyle: "italic",
        color: "text",
        fontWeight: 900,
        boxShadow: `inset 0 -4px 0 ${colors.common.green}`,
      },
      em: {
        fontStyle: "italic",
        color: colors.common.purple,
        fontWeight: 900,
      },
      img: {
        display: "block",
        // marginTop: "20px",
        maxWidth: "80%",
        objectFit: "cover",
        margin: "0 auto",
        marginTop: "2.5rem",
        marginBottom: "2.5rem",
      },
      p: {
        fontStyle: "normal",
        color: "text",
        fontWeight: 500,
      },
      ol: {
        color: "text",
        paddingLeft: "25px",
        fontWeight: 600,
        marginBottom: "10px",
      },
      ul: {
        color: "text",
        paddingLeft: "25px",
        listStyleType: "square",
        fontWeight: 600,
      },
      hr: {
        borderBottom: `1px solid ${colors.common.gray}`,
      },
    },
    prism: {
      dark: {
        plain: {
          whiteSpace: "pre-wrap",
          backgroundColor: "#22262f",
        },
      },
      light: {
        plain: {
          whiteSpace: "pre-wrap",
        },
      },
    },
  },
};
